# Generated by Django 5.1.2 on 2024-10-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_contact_message_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='address',
        ),
    ]
